# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d832b6c15c4af28d47d00d4a3799fc1f878eabcbde07c72075620e9e89c9a672c6800c14e9de196608fe3c277e42fb6bc8ff3986956a8a46f250949aa4ae940a

test:
  secret_key_base: 64a1b135e540cbc15ac45bf4f39aaee36d64f95f69eeecc7dac4d5df2a617b4254ef58742e05f7118c70b98890089e709d8d7a0197901dc6606f78a076d5552a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
